bcgov/nr-bcws-wfnews

- server/pom.xml
- server/wfnews-api-rest-endpoints/src/test/java/ca/bc/gov/nrs/wfnews/api/rest/v1/endpoints/CheckHealthEndpointsTest.java
See description. A small fix so builds complete without test failures (no -DskipTests), postgres and spring dependencies have been updated
> Spring/Postgres update, fix failing stub unit test

- client/wfnews-war/pom.xml
- client/wfnews-war/src/main/angular/src/app/app.component.scss
- client/wfnews-war/src/main/angular/src/app/app.module.ts
- client/wfnews-war/src/main/angular/src/app/app.routing.ts
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/admin-incident-form.component.html
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/admin-incident-form.component.scss
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/admin-incident-form.component.ts
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/incident-details-panel/incident-details-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/incident-details-panel/incident-details-panel.component.scss
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/incident-details-panel/incident-details-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/utils/index.ts
- client/wfnews-war/src/main/angular/src/assets/data/appConfig.json
[WFNEWS-348](https://apps.nrs.gov.bc.ca/int/jira/browse/WFNEWS-348)
Adding the Initial component, header (sticky) and acordions.
No styling is applied at the moment, and a test data stub is included until API wiring can be done.
> WFNEWS-348

- client/wfnews-war/src/main/angular/src/app/app.component.html
- client/wfnews-war/src/main/angular/src/app/app.module.ts
Waiting on logout button implementation
> Remove logout from wfcc common

- client/wfnews-war/src/main/angular/src/app/app.component.ts
- client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.html
Fixes for Non-Compliance label changes
> Non compliance tickets 414, 408, 402, 400

- client/wfnews-war/src/main/angular/package.json
- client/wfnews-war/src/main/angular/src/app/app.module.ts
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/admin-incident-form.component.html
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/admin-incident-form.component.ts
Initial implementation of Rich Text editor
This does not include wiring for Save/Publish to the API yet
> Add Tab on incident form, add rich text editor

- client/wfnews-war/src/main/angular/src/app/app.module.ts
- client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.html
- client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.scss
- client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.ts
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/admin-incident-form.component.scss
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/area-restrictions-details-panel/area-restrictions-details-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/evac-orders-details-panel/evac-orders-details-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/panel-evacuation-orders-and-alerts/panel-evacuation-orders-and-alerts.component.html
- client/wfnews-war/src/main/angular/src/app/components/panel-wildfire-stage-of-control/panel-wildfire-stage-of-control.component.html
- client/wfnews-war/src/main/angular/src/app/services/AGOL-service.ts
- client/wfnews-war/src/main/angular/src/assets/data/appConfig.json
- client/wfnews-war/src/main/webapp/config.jsp
Cleanup for the Non compliance tickets:
WFNEWS-403, 401, 398, 397
Additionally, moved AGOL queries into a service class
> Non compliance cleanup

- client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.html
- client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.scss
- client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.ts
- client/wfnews-war/src/main/angular/src/app/services/common-utility.service.ts
Still need to implement zoom in current location. Check this in for Gabriel's  WFNEWS-155
> wip WFNEWS-260

- client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.html
- client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/active-wildfires.config.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/area-restrictions.config.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/bans-and-prohibitions.config.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/bc-fire-centres.config.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/bcws-activefires-publicview-inactive.config.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/closed-recreation-sites.config.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/danger-rating.config.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/drive-bc-active-events.config.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/evacuation-orders-and-alerts-wms.config.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/fire-perimeters.config.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/prescribed-fire.config.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/map.config.ts
- client/wfnews-war/src/main/angular/src/app/services/wf-map.service.ts
- client/wfnews-war/src/main/angular/src/styles/main.scss
> WFNEWS-423, 428, 429: Add identify panels for Bans, Evac and Area restrictions

- client/wfnews-war/src/main/angular/src/styles/main.scss
After discussion with Jacqueline
> Style tweaks for popup

- client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.html
- client/wfnews-war/src/main/angular/src/styles/_base.scss
removed commented out code from active-wildfire-map.component
> footer links wrong color fixed

- .vscode/settings.json
- client/pom.xml
- client/wfnews-war/pom.xml
- client/wfnews-war/src/main/java/ca/bc/gov/nrs/wfnews/spring/TokenServiceSpringConfig.java
- client/wfnews-war/src/main/java/ca/bc/gov/nrs/wfnews/web/controller/CheckTokenController.java
- client/wfnews-war/src/main/resources/static.properties
I have touched base with Chris P about secret placeholder {webade-oauth2.wfim-incident-manager-ui.client.secret}
> checkToken update

- client/wfnews-war/src/main/resources/static.properties
I see there is console error on dev admin 
"Http failure during parsing for https://wfnews-client.dev.bcwildfireservices.com//checkToken.jsp","
> get rid of / in properties file

- client/wfnews-war/src/main/java/ca/bc/gov/nrs/wfnews/spring/TokenServiceSpringConfig.java
- client/wfnews-war/src/main/resources/application.properties
- client/wfnews-war/src/main/resources/static.properties
- client/wfnews-war/src/main/webapp/config.jsp
Accidently closed the previous one.... re-open with unused properties removed
> Use System variables

- client/wfnews-war/src/main/webapp/wfdmProxy.jsp
And remove the session. We don't need stateful sessions
> Get the token from the request, not the session

- client/pom.xml
- server/wfnews-service-api/pom.xml
2.11 Unavailable in ministry artifactory
> Rollback commons

- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/index.ts
Missing comma missed on conflict merge
> Add missing comma

- database/main-changelog.json
- database/scripts/01_00_00/03/ddl/tables/MODIFY.PUBLISHED_INCIDENT_DETAIL.sql
- database/scripts/01_00_00/03/docs/Readme.txt
- server/wfnews-api-rest-endpoints/src/main/java/ca/bc/gov/nrs/wfnews/api/rest/v1/endpoints/ExternalUriEndpoint.java
- server/wfnews-api-rest-endpoints/src/main/java/ca/bc/gov/nrs/wfnews/api/rest/v1/endpoints/PublicPublishedIncidentEndpoint.java
- server/wfnews-api-rest-endpoints/src/main/java/ca/bc/gov/nrs/wfnews/api/rest/v1/endpoints/PublishedIncidentEndpoint.java
- server/wfnews-api-rest-endpoints/src/main/java/ca/bc/gov/nrs/wfnews/api/rest/v1/endpoints/impl/ExternalUriEndpointImpl.java
- server/wfnews-api-rest-endpoints/src/main/java/ca/bc/gov/nrs/wfnews/api/rest/v1/endpoints/impl/PublicPublishedIncidentEndpointImpl.java
- server/wfnews-api-rest-endpoints/src/main/java/ca/bc/gov/nrs/wfnews/api/rest/v1/endpoints/impl/PublishedIncidentEndpointImpl.java
- server/wfnews-persistence/src/main/java/ca/bc/gov/nrs/wfnews/persistence/v1/dao/BaseDao.java
- server/wfnews-persistence/src/main/java/ca/bc/gov/nrs/wfnews/persistence/v1/dao/PublishedIncidentDao.java
- server/wfnews-persistence/src/main/java/ca/bc/gov/nrs/wfnews/persistence/v1/dao/mybatis/ExternalUriDaoImpl.java
- server/wfnews-persistence/src/main/java/ca/bc/gov/nrs/wfnews/persistence/v1/dao/mybatis/PublishedIncidentDaoImpl.java
- server/wfnews-persistence/src/main/java/ca/bc/gov/nrs/wfnews/persistence/v1/dao/mybatis/mapper/PublishedIncidentMapper.java
- server/wfnews-persistence/src/main/resources/ca/bc/gov/nrs/wfnews/persistence/v1/dao/mybatis/mapper/PublishedIncidentMapper.xml
- server/wfnews-service-api/src/main/java/ca/bc/gov/nrs/wfnews/service/api/v1/IncidentsService.java
- server/wfnews-service-api/src/main/java/ca/bc/gov/nrs/wfnews/service/api/v1/impl/IncidentsServiceImpl.java
And indexes. Also some tweaks for the query to fetch data as geojson
> DB Update, Add missing attributes

- server/wfnews-persistence/src/main/resources/ca/bc/gov/nrs/wfnews/persistence/v1/dao/mybatis/mapper/PublishedIncidentMapper.xml
Add missing schema qualifier to mappers for json queries
> Add schema to mapper

- client/wfnews-war/src/main/angular/src/app/app.module.ts
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/image-gallery-panel/image-gallery-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/maps-panel/maps-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/base/base.component.ts
- client/wfnews-war/src/main/angular/src/app/components/incident-identify-panel/incident-identify-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/incident-identify-panel/incident-identify-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/panel-fire-danger/panel-fire-danger.component.scss
- client/wfnews-war/src/main/angular/src/app/components/panel-wildfire-stage-of-control/panel-wildfire-stage-of-control.component.html
- client/wfnews-war/src/main/angular/src/app/components/panel-wildfire-stage-of-control/panel-wildfire-stage-of-control.component.ts
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-info-header/incident-header-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-info-header/incident-header-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/sticky-widget/sticky-widget.component.html
- client/wfnews-war/src/main/angular/src/app/components/sticky-widget/sticky-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/sticky-widget/sticky-widget.component.ts
- client/wfnews-war/src/main/angular/src/app/components/wildfires-list/wildfires-list.component.desktop.html
- client/wfnews-war/src/main/angular/src/app/components/wildfires-list/wildfires-list.component.ts
- client/wfnews-war/src/main/angular/src/app/services/local-storage-service.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/clab-indian-reserves.config.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/fnt-treaty-land.config.ts
- client/wfnews-war/src/main/angular/src/app/services/watchlist-service.ts
Implement local store service, watchlist service, watchlist UI
> WFNEWS-253

- client/wfnews-war/src/main/angular/package-lock.json
- client/wfnews-war/src/main/angular/src/app/app.module.ts
- client/wfnews-war/src/main/angular/src/app/app.routing.ts
- client/wfnews-war/src/main/angular/src/app/components/current-alert-component/current-alert-component.component.html
- client/wfnews-war/src/main/angular/src/app/components/current-alert-component/current-alert-component.component.scss
- client/wfnews-war/src/main/angular/src/app/components/current-alert-component/current-alert-component.component.ts
- client/wfnews-war/src/main/angular/src/app/components/panel-evacuation-orders-and-alerts/panel-evacuation-orders-and-alerts.component.html
- client/wfnews-war/src/main/angular/src/app/components/wildfires-list-header/wildfires-list-header.component.html
- client/wfnews-war/src/main/angular/src/app/components/wildfires-list-header/wildfires-list-header.component.scss
- client/wfnews-war/src/main/angular/src/app/components/wildfires-list-header/wildfires-list-header.component.spec.ts
- client/wfnews-war/src/main/angular/src/app/components/wildfires-list-header/wildfires-list-header.component.ts
- client/wfnews-war/src/main/angular/src/app/components/wildfires-list/wildfires-list.component.desktop.html
- client/wfnews-war/src/main/angular/src/app/components/wildfires-list/wildfires-list.component.desktop.scss
- client/wfnews-war/src/main/angular/src/app/components/wildfires-list/wildfires-list.component.ts
Checking in first half of the component, 
toggle, filter and list update in progress.
> current-alert-tab part 1

- client/wfnews-war/src/main/angular/src/app/components/current-alert-component/current-alert-component.component.scss
Why were these removed? Removing them breaks the responsive panels!?!
> Add back another removed flex-wrap

- client/wfnews-war/src/main/angular/src/app/components/sticky-widget/contact-widget-dialog/contact-widget-dialog.component.ts
- server/wfnews-api-rest-common/src/main/java/ca/bc/gov/nrs/wfnews/api/rest/v1/resource/MailResource.java
Mail subtype missing in request
> Add missing mail type

- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/admin-incident-form.component.ts
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/evac-orders-details-panel/evac-orders-details-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/image-gallery-panel/image-gallery-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/video-gallery-panel/video-gallery-panel.component.ts
- database/data-resync.py
Specifically for the source object ID
> Change external uri from incident number to incident guid

- client/wfnews-war/src/main/angular/src/app/interceptors/wfnews-interceptor.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layer-display.config.ts
Added the weather station layer to the layer list, added override in interceptor to prevent adding login to pointid
> WFNEWS-842: Display layer in list, fix interceptor

- client/wfnews-war/src/main/angular/src/index.html
Ticket specified removing title and updating logo, however a secondary request from Briana was "just remove the splash screen". So this is the removal, we can test for startup performance.
> WFNEWS-765: Remove splash screen

- client/wfnews-war/pom.xml
- client/wfnews-war/src/main/angular/src/app/components/sticky-widget/sticky-widget.component.scss
Updated z-index to place watchlist above incident popup
> WFNEWS-785: Prevent watchlist from displaying below popup

- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/maps-panel/maps-panel.component.ts
Attachment title was missing on the Map create resource. Title added
> WFNEWS-822: Add attachmentTitle on attachment create

- client/wfnews-war/src/main/angular/src/app/app.component.html
- client/wfnews-war/src/main/angular/src/app/app.component.scss
- client/wfnews-war/src/main/angular/src/app/app.component.ts
Added panel to main window to display PM download on small screens
> WFNEWS-691: Add default PM download on small screens

- client/wfnews-war/src/main/angular/src/app/app.component.ts
WFNEWS-691: To check portrait and landscape views, change from <= to just <
> WFNEWS-691: Update PM Redirect

- client/wfnews-war/src/main/angular/src/app/components/panel-wildfire-stage-of-control/panel-wildfire-stage-of-control.component.ts
- client/wfnews-war/src/main/angular/src/app/components/wildfires-list/wildfires-list.component.desktop.html
- client/wfnews-war/src/main/angular/src/app/components/wildfires-list/wildfires-list.component.ts
- server/wfnews-persistence/src/main/resources/ca/bc/gov/nrs/wfnews/persistence/v1/dao/mybatis/mapper/PublishedIncidentMapper.xml
Working live with Paul P. to clear out some filter issues
> Various minor non-compliance updates

- client/wfnews-war/src/main/angular/src/app/components/panel-wildfire-stage-of-control/panel-wildfire-stage-of-control.component.html
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-info-header/incident-header-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-info-panel/incident-info-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/wildfires-list/wildfires-list.component.desktop.html
- client/wfnews-war/src/main/angular/src/app/components/wildfires-list/wildfires-list.component.desktop.ts
- client/wfnews-war/src/main/angular/src/app/store/wildfiresList/wildfiresList.action.ts
- client/wfnews-war/src/main/angular/src/assets/data/appConfig.json
- database/main-changelog.json
- database/scripts/01_00_00/05/ddl/tables/MODIFY.PUBLISHED_INCIDENT_DETAIL.sql
- database/scripts/01_00_00/05/docs/Readme.txt
- load-testing/WFNEWS_Load_Test.jmx
- load-testing/WFNEWS_Load_Test_2.jmx
- load-testing/WFNEWS_Load_Test_2_Cloudfront.jmx
- load-testing/WFNEWS_Load_Test_2_No_Cloudfront.jmx
- server/wfnews-api-rest-common/src/main/java/ca/bc/gov/nrs/wfnews/api/rest/v1/resource/PublishedIncidentResource.java
- server/wfnews-api-rest-common/src/main/java/ca/bc/gov/nrs/wfnews/api/rest/v1/resource/SimplePublishedIncidentResource.java
- server/wfnews-api-rest-endpoints/src/main/java/ca/bc/gov/nrs/wfnews/api/rest/v1/endpoints/PublicPublishedIncidentEndpoint.java
- server/wfnews-api-rest-endpoints/src/main/java/ca/bc/gov/nrs/wfnews/api/rest/v1/endpoints/impl/PublicPublishedIncidentEndpointImpl.java
- server/wfnews-api-rest-endpoints/src/main/java/ca/bc/gov/nrs/wfnews/api/rest/v1/endpoints/impl/PublishedIncidentEndpointImpl.java
- server/wfnews-api-rest-endpoints/src/main/java/ca/bc/gov/nrs/wfnews/api/rest/v1/resource/factory/PublishedIncidentResourceFactory.java
- server/wfnews-model/src/main/java/ca/bc/gov/nrs/wfnews/api/model/v1/SimplePublishedIncident.java
- server/wfnews-persistence/src/main/java/ca/bc/gov/nrs/wfnews/persistence/v1/dao/PublishedIncidentDao.java
- server/wfnews-persistence/src/main/java/ca/bc/gov/nrs/wfnews/persistence/v1/dao/mybatis/PublishedIncidentDaoImpl.java
- server/wfnews-persistence/src/main/java/ca/bc/gov/nrs/wfnews/persistence/v1/dto/PublishedIncidentDto.java
- server/wfnews-persistence/src/main/resources/ca/bc/gov/nrs/wfnews/persistence/v1/dao/mybatis/mapper/PublishedIncidentMapper.xml
- server/wfnews-service-api/src/main/java/ca/bc/gov/nrs/wfnews/service/api/v1/IncidentsService.java
- server/wfnews-service-api/src/main/java/ca/bc/gov/nrs/wfnews/service/api/v1/impl/IncidentsServiceImpl.java
Accidently closed the previous one... 
The PR includes adding fire_centre_name column, alter the fire_centre column to fire_centre_code. update the comments. 
And apply the api updates to these db changes. 
Also ran the news api locally to test the changes, verify the orderBy fireCentreName works and confirm data populated
> Wfnews 814 

- client/wfnews-war/src/main/angular/src/app/components/wf-admin-panel/wf-admin-panel.component.desktop.html
- client/wfnews-war/src/main/angular/src/app/components/wf-admin-panel/wf-admin-panel.component.desktop.ts
- client/wfnews-war/src/main/angular/src/app/store/incidents/incidents.effects.ts
WFIM-API's orderBy has also been updated as well.
> sort by lastUpdatedTimeStamp

- client/wfnews-war/src/main/angular/src/app/services/published-incident-service.ts
- client/wfnews-war/src/main/angular/src/app/store/wildfiresList/wildfiresList.effects.ts
- client/wfnews-war/src/main/angular/src/assets/data/appConfig.json
- client/wfnews-war/src/main/webapp/config.jsp
- server/wfnews-api-rest-endpoints/src/main/java/ca/bc/gov/nrs/wfnews/api/rest/v1/spring/AppConfig.java
Updates to UI to pass the apiKey header, add key to config.jsp. Update API to accept apiKey header
> WFNEWS-892: Use API gateway key

- client/wfnews-war/src/main/angular/src/app/app.component.html
- client/wfnews-war/src/main/angular/src/app/app.component.ts
- client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.ts
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/image-gallery-panel/image-card-component/image-card-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/image-gallery-panel/image-gallery-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/image-gallery-panel/image-gallery-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/incident-details-panel/incident-details-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/video-gallery-panel/video-card-component/video-card-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/video-gallery-panel/video-card-component/video-card-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/video-gallery-panel/video-gallery-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/admin-incident-form/video-gallery-panel/video-gallery-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/incident-identify-panel/incident-identify-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-gallery-panel/incident-gallery-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-gallery-panel/incident-gallery-panel.component.scss
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-info-header/incident-header-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-info-header/incident-header-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-info-panel/incident-info-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-info-panel/incident-info-panel.component.scss
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-info-panel/incident-info-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-overview-panel/incident-overview-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/public-incident-page.component.scss
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/public-incident-page.component.ts
- client/wfnews-war/src/main/angular/src/app/utils/index.ts
- client/wfnews-war/src/main/angular/src/index.html
- server/wfnews-persistence/src/main/resources/ca/bc/gov/nrs/wfnews/persistence/v1/dao/mybatis/mapper/PublishedIncidentMapper.xml
Addressing the following tickets:
WFNEWS-941
WFNEWS-915
WFNEWS-940
WFNEWS-944
WFNEWS-916
WFNEWS-914
WFNEWS-938
WFNEWS-919
> UAT remediation fixes and updates

- client/wfnews-war/src/main/angular/src/app/components/wf-stats-component/wf-stats.component.ts
- client/wfnews-war/src/main/angular/src/app/services/published-incident-service.ts
There are cases where the Fire Centre Name or Code were not set, causing miscounts
> Fix for stats counts

- client/wfnews-war/src/main/angular/src/app/store/incidents/incidents.effects.ts
This makes me upset. Never hard-code these kinds of magic numbers, especially something that changes each year.
> Fix hardcoded fire year

- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/bc-parks-closures.config.ts
Add an identify popup for the protected lands layer
> Add protected Lands popup

- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layer-display.config.ts
Move protected sites layer above rec sites closures
> Move protected sites layer

- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layer-display.config.ts
Remove protected lands inline legend
> Remove protected lands inline legend

- client/wfnews-war/src/main/angular/src/app/components/wf-stats-component/wf-stats.component.ts
Hide the "OUT" bar on the active fires status bar graph
> Hide "out" on active fire status chart

- client/wfnews-war/src/main/angular/src/app/components/wf-stats-component/wf-stats.component.ts
Update OUT fire calculation to also limit to current fire year
> WFNEWS-1169

- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-gallery-panel/incident-gallery-panel.component.html
Removed 20 second limit on youtube viewer
> Remove youtube viewer run limit

- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-info-header/incident-header-panel.component.scss
Evac colour update on details page
> Update evac colour

- .github/workflows/deploy-dev.yml
- client/wfnews-war/src/main/angular/src/assets/data/appConfig.json
Paul is having a tough time testing because the old API is token restricted. This should unblock him for the time being.
> WFNEWS-1175 : Change dev env for AGOL

- .github/workflows/deploy-dev.yml
- .github/workflows/lambda-zip.yml
- terraform/lambda.tf
Updated lambda process to zip in action before terraform handler
> Lamba process update

- terraform/lambda.tf
Temporarily ignore lambda promotion
> Temp ignore lambda

- .github/workflows/lambda-zip.yml
Disable lambda-zip AWS bucket write temporarily
> disable lambda-zip

- client/wfnews-war/src/main/angular/src/app/components/report-of-fire/contact-page/rof-contact-page.component.ts
- client/wfnews-war/src/main/angular/src/app/components/report-of-fire/simple-question-page/rof-simple-question-page.component.ts
- client/wfnews-war/src/main/angular/src/app/components/report-of-fire/title-page/rof-title-page.component.ts
(ideally it should check in RoFPage component, But the way our QA will test it is to turn on the airplane mode after they open the app. So I put the checker into each page
> check browser online status

- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/overview-widget/overview-widget.component.html
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/overview-widget/overview-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/overview-widget/overview-widget.component.ts
- client/wfnews-war/src/main/angular/src/app/services/published-incident-service.ts
> WFNEWS-1491

- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/active-fires-widget/active-fires-widget.component.html
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/active-fires-widget/active-fires-widget.component.scss
Mobile styling updates for Active fires widget
> WFNEWS-1492: mobile styling

- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/active-fires-widget/active-fires-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/bans-widget/bans-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/blog-widget/blog-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/evacuations-widget/evacuations-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/evacuations-widget/evacuations-widget.component.ts
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/fire-cause-widget/fire-cause-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/fire-centre-stats-widget/fire-centre-stats-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/fire-totals-widget/fire-totals-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/historical-comparison-widget/historical-comparison-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/overview-widget/overview-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/resources-widget/resources-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/situation-widget/situation-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/videos-widget/videos-widget.component.scss
> WFNEWS-1494

- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/dashboard.component.html
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/blog-widget/blog-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/fire-cause-widget/fire-cause-widget.component.html
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/fire-cause-widget/fire-cause-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/fire-cause-widget/fire-cause-widget.component.ts
Merger for yearly/current cause stats
> WFNEWS-1498, 1505

- client/wfnews-war/src/main/angular/src/app/components/wildfires-list-header/filter-by-location/filter-by-location-dialog.component.html
> Clear location text

- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/active-fires-widget/active-fires-widget.component.html
Include learn more link for stage of control info page
> active-fires-widget

- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/active-fires-widget/active-fires-widget.component.ts
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/fire-cause-widget/fire-cause-widget.component.ts
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/fire-centre-stats-widget/fire-centre-stats-widget.component.ts
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/historical-comparison-widget/historical-comparison-widget.component.html
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/historical-comparison-widget/historical-comparison-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/historical-comparison-widget/historical-comparison-widget.component.ts
- client/wfnews-war/src/main/angular/src/app/services/published-incident-service.ts
Initial historical widget layout.
Current fetching 20-Year average via a brute force fetch of 20 year history data, but this will likely change with a new endpoint specific for calculating these on the DB side.
> WFNEWS-1507

- client/wfnews-war/src/main/angular/src/app/app.component.ts
- client/wfnews-war/src/main/angular/src/app/components/draggable-panel/draggable-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/draggable-panel/draggable-panel.component.ts
adding closed recreation sites, drive-bc-active-events to preview
> Wfnews 1340

- client/wfnews-war/src/main/angular/src/app/components/draggable-panel/draggable-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/draggable-panel/draggable-panel.component.ts
> wfnews-1342

- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-info-panel/incident-info-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-info-panel/incident-info-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-overview-panel/incident-overview-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-overview-panel/incident-overview-panel.component.scss
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-overview-panel/incident-overview-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/public-incident-page.component.html
Move the "Response Type" section to the new Response Tab
Move the "Response" section to the new Response Tab
Move the "Current Resources" section to the new response tab
> wfnews-1570

- client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.scss
> WFNEWS-1663

- client/wfnews-war/src/main/angular/src/app/components/legend-panels/road-event-layers/road-event-legend.component.html
Update road event descriptions
> WFNEWS-1665

- client/wfnews-war/src/main/angular/package.json
- client/wfnews-war/src/main/angular/src/app/app.component.scss
- client/wfnews-war/src/main/angular/src/app/app.component.ts
- client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.ts
- client/wfnews-war/src/main/angular/src/app/components/search/search-page.component.ts
Cleanup for some non-compliance issues, desktop search updates
> Non compliance

- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/dashboard.component.html
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/dashboard.component.ts
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/fire-centre-stats-widget/fire-centre-stats-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/fire-totals-widget/fire-totals-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/fires-of-note-widget/fires-of-note-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/resources-widget/resources-widget.component.scss
- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/videos-widget/videos-widget.component.scss
- server/wfnews-api/wfnews-service-api/src/main/java/ca/bc/gov/nrs/wfnews/service/api/v1/impl/IncidentsServiceImpl.java
Also, disable offseason check on dashboard for testing.
> Dashboard padding

- client/wfnews-war/src/main/angular/src/app/components/saved/add-saved-location/add-saved-location.component.scss
- client/wfnews-war/src/main/angular/src/app/components/saved/saved-location-full-details/saved-location-full-details.component.html
- client/wfnews-war/src/main/angular/src/app/components/saved/saved-location-full-details/saved-location-full-details.component.scss
- client/wfnews-war/src/main/angular/src/app/components/saved/saved-location-weather-details/saved-location-weather-details.component.html
- client/wfnews-war/src/main/angular/src/app/components/saved/saved-location-weather-details/saved-location-weather-details.component.scss
- client/wfnews-war/src/main/angular/src/app/components/saved/saved-location-weather-details/saved-location-weather-details.component.ts
- client/wfnews-war/src/main/angular/src/app/components/saved/saved.component.scss
- client/wfnews-war/src/main/angular/src/app/components/wildfire-resources/wf-resources.component.scss
Add precipitation to Weather details
Adjustments for some padding and container sizes
Adding hovers to nav buttons
> WFNEWS-1742

- client/wfnews-war/src/main/angular/src/app/components/full-details/area-restrictions-full-details/area-restrictions-full-details.component.html
- client/wfnews-war/src/main/angular/src/app/components/full-details/area-restrictions-full-details/area-restrictions-full-details.component.ts
- client/wfnews-war/src/main/angular/src/app/components/full-details/evac-alert-full-details/evac-alert-full-details.component.html
- client/wfnews-war/src/main/angular/src/app/components/full-details/evac-alert-full-details/evac-alert-full-details.component.ts
- client/wfnews-war/src/main/angular/src/app/components/full-details/evac-order-full-details/evac-order-full-details.component.html
- client/wfnews-war/src/main/angular/src/app/components/saved/saved-location-full-details/saved-location-full-details.component.html
- client/wfnews-war/src/main/angular/src/app/components/saved/saved-location-full-details/saved-location-full-details.component.ts
Personally, I think the bookmark icon on these pages should not be clickable. Users can always navigate to the wildfire detail page to save or unsave it, or unsave it from the 'Saved Locations' page.
> wfnews-1795

- client/wfnews-war/src/main/angular/src/app/components/wf-admin-panel/dashboard-panel/edit-dashboard.component.ts
- client/wfnews-war/src/main/angular/src/app/services/published-incident-service.ts
Simple handler to detect if there are multiple published reports, and if there are iterate through them and set them to archived/unpublished
> Handle duplicate situation reports

- client/wfnews-war/src/main/angular/src/app/services/wf-map.service.ts
Not 100% sure if this could help on IOS http call issue to openMaps. But maybe worth a try
> making same-origin mode by default.

- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layer-display.config.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/fuel-treatment.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/index.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/prescribed-fire.config.ts
- server/wfnews-api/wfnews-api-rest-endpoints/src/main/java/ca/bc/gov/nrs/wfnews/api/rest/v1/endpoints/impl/StatisticsEndpointImpl.java
Cache no longer needed, updates to cloudfront should mitigate its use
> Add treatment, remove stats memory cache

- server/wfnews-api/wfnews-persistence/src/main/resources/ca/bc/gov/nrs/wfnews/persistence/v1/dao/mybatis/mapper/StatisticsMapper.xml
Minor update to the structure of the stats query to prevent unnecessary unions when loading single fire centre results
> Improve stats query on single centre fetches

- client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layer-display.config.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/bc-fire-centres.config.ts
- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layers/index.ts
These layers are not going to be ready and may not be appropriate for display to public until later in the fire season
> Hide Fuel Treatment and Prescribed fires layers

- client/wfnews-war/src/main/angular/src/app/services/map-config.service/layer-display.config.ts
> Hide Fire Zones

- client/wfnews-war/src/main/angular/src/app/services/wf-map.service.ts
Set prefer canvas renderer on vector layer creation
> WFNEWS-2051: Vector Tile to Canvas

- client/wfnews-war/src/main/angular/src/app/components/draggable-panel/draggable-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/incident-identify-panel/incident-identify-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-info-header/incident-header-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/saved/saved-location-weather-details/saved-location-weather-details.component.html
- client/wfnews-war/src/main/angular/src/app/components/weather/weather-history/weather-history.component.ts
- client/wfnews-war/src/main/angular/src/app/components/weather/weather-panel/weather-panel.component.html
- client/wfnews-war/src/main/angular/src/app/components/weather/weather-panel/weather-panel.component.ts
- client/wfnews-war/src/main/angular/src/app/components/wf-map-container/wf-map-container.component.ts
- client/wfnews-war/src/main/angular/src/app/services/point-id.service/interfaces.ts
Update Evac icons for desktop identify/details panels
> WFNEWS-2020: Update Evac icons for desktop identify/details panels

- client/wfnews-war/src/main/angular/src/app/components/dashboard-component/widgets/overview-widget/overview-widget.component.ts
Update overview map error handling
> WFNEWS-2040

- client/wfnews-war/src/main/angular/src/app/components/saved/saved-location-weather-details/saved-location-weather-details.component.html
- client/wfnews-war/src/main/angular/src/app/components/saved/saved-location-weather-details/saved-location-weather-details.component.scss
- client/wfnews-war/src/main/angular/src/app/components/weather/weather-panel/weather-panel.component.html
> add fire danger class button

- client/wfnews-war/src/main/angular/src/app/components/active-wildfire-map/active-wildfire-map.component.ts
- client/wfnews-war/src/main/angular/src/app/components/map-layers-drawer-section/map-layers-drawer-section.component.html
- client/wfnews-war/src/main/angular/src/app/components/map-layers-drawer-section/map-layers-drawer-section.component.ts
> wfnews-2032 map_layer_selection: when they select an individual map layer

- client/wfnews-war/src/main/angular/src/app/components/full-details/area-restrictions-full-details/area-restrictions-full-details.component.ts
- client/wfnews-war/src/main/angular/src/app/components/full-details/bans-full-details/bans-full-details.component.ts
- client/wfnews-war/src/main/angular/src/app/components/full-details/danger-rating-full-details/danger-rating-full-details.component.ts
- client/wfnews-war/src/main/angular/src/app/components/full-details/evac-alert-full-details/evac-alert-full-details.component.ts
- client/wfnews-war/src/main/angular/src/app/components/public-incident-page/incident-info-header/incident-header-panel.component.ts
Increasing radii for fetching the surrounding incidents on mobile full details pages as I noticed some incidents were missing
> WFNEWS-2144 remove area restrction centroid & increase radii for surrounding incidents

- lambda/active-fire-monitor/active_fire/app.py
- lambda/area-restrictions-monitor/area-restrictions/app.py
- lambda/bans-and-prohibitions-monitor/bans-and-prohibitions/app.py
- lambda/evacuation-orders-monitor/evacuation-orders/app.py
Add handling for no new data, timeout
> WFNEWS-2012
